# Assignment Day 10 | 11th September 2020

## Question 1:
### Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [1]:
import numpy as np

In [2]:
x = np.array([3, 5])
y = np.array([2, 5])
print(x,y)

[3 5] [2 5]


In [5]:
print("Comparison - greater:-", np.greater(x, y))
print("Comparison - greater_equal:-", np.greater_equal(x, y))
print("Comparison - less:-", np.less(x, y))
print("Comparison - less_equal:-", np.less_equal(x, y))

Comparison - greater:- [ True False]
Comparison - greater_equal:- [ True  True]
Comparison - less:- [False False]
Comparison - less_equal:- [False  True]


## Question 2:
### Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [15]:
x = np.zeros(10)
y = np.ones(10)
z = np.full(10,5)
print(x)
print(y)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


## Question 3:
### Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [16]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [19]:
print("Sum of each column:- ",np.sum(a, axis=0))
print("Sum of each row:- ",np.sum(a, axis=1))

Sum of each column:-  [5 7 9]
Sum of each row:-  [ 6 15]


## Question 4:
### Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [28]:
x = np.array([1,2,3])
y = np.array([4,5,6])

adding = print(np.add(x,y))
subtracting =print(np.subtract(x,y))
multiplying = print(np.multiply(x,y))
dividing = print(np.divide(x,y))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## Question 5:
### Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

In [37]:
x = np.array([0,30,45,60,90])

s = print("Sin :-", np.sin(x)*np.pi/180)
c = print("Cos :-", np.cos(x)*np.pi/180)
t = print("Tan :-", np.tan(x)*np.pi/180)

Sin :- [ 0.         -0.0172444   0.01485107 -0.00531995  0.01560319]
Cos :- [ 0.01745329  0.0026922   0.0091686  -0.01662274 -0.00782036]
Tan :- [ 0.         -0.11179412  0.02827041  0.00558576 -0.03482282]


## Question 6:
### Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels

In [40]:
import pandas as pd

In [45]:
data  = {'name': ['Tejus', 'Ram', 'Shaam', 'Shubham', 'Chiku'],
        'score': [50, 60, 70, 80, 90],
        'attempts': [3,2,1,2,3],
        'qualify': ['yes', 'no', 'yes', 'no', 'no']}
labels = ['1','2','3','4','5']

df = pd.DataFrame(data , index=labels)
print(df)

      name  score  attempts qualify
1    Tejus     50         3     yes
2      Ram     60         2      no
3    Shaam     70         1     yes
4  Shubham     80         2      no
5    Chiku     90         3      no
